"""
    Problem 2

    Even Fibonacci numbers

    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
"""

fi_a = 1
fi_b = 2
fi_z = 3
sum = 2  # Поскольку ниже проверяем элементы начиная с третьего, в сумму сразу записываем первое четное число

while 1:
    if not fi_z % 2:
        sum += fi_z
    fi_z = fi_a + fi_b
    fi_a = fi_b
    fi_b = fi_z
    if fi_z >= 4000000:
        break

print(sum)
